#!/bin/bash

APP="$(pwd)/.build/bundle"
SCRIPT="$APP/main.js"
PID="$APP/fileer.pid"
LOG="$APP/fileer.log"

#remove .build 
rm -rf .build 

# meteor build  and extract
meteor build .build
cd .build
tar -xvf fileer.tar.gz

# npm install dep
cd bundle/programs/server
npm install

# exports 
export PORT=5000
export MONGO_URL="mongodb://localhost:27017/fileer"
export ROOT_URL="https://fileer.com"
export DISABLE_WEBSOCKETS=true

forever stop $SCRIPT
forever start -p $APP --pidFile $PID -l $LOG -a -d $SCRIPT
