#!/bin/bash

# CORE BUNDLES VARIABLES
APPNAME="fileer"
VERSION=$(date +%Y-%m-%d-%T) # version name
BUNDLES="/home/yasaricli/projects/builds"
FILEER="$BUNDLES/fileer"
APP="$FILEER/$VERSION"

# FOREVER VARIABLES
SCRIPT="$APP/main.js"
PID="$APP/fileer.pid"
LOG="$APP/fileer.log"
PID="$APP/fileer.pid"

#CURRENT VERSION 
CURRENT_VERSION_FILE="$FILEER/fileer.version"
CURRENT_VERSION=$(cat $FILEER/fileer.version)
CURRENT_APP="$FILEER/$CURRENT_VERSION"
CURRENT_SCRIPT="$CURRENT_APP/main.js"
CURRENT_PID="$CURRENT_APP/fileer.pid"
CURRENT_LOG="$CURRENT_APP/fileer.log"

# EXPORT ENVS
export PORT=3000
export ROOT_URL="https://fileer.com"
export MONGO_URL="mongodb://localhost:27017/fileer"
export DISABLE_WEBSOCKETS=true


eko() {
    echo -e "\n\n $1 \n\n"
}

currentVersion() {
    eko "\n\n -- VERSION: $CURRENT_VERSION -- \n\n"
}

stopCurrentVersion() {
    forever stop $CURRENT_SCRIPT
}

restartCurrentVersion() {
    stopCurrentVersion
    forever start -p $CURRENT_APP --pidFile $CURRENT_PID -l $CURRENT_LOG -a -d $CURRENT_SCRIPT
}

startCurrentVersion() {
    forever start -p $CURRENT_APP --pidFile $CURRENT_PID -l $CURRENT_LOG -a -d $CURRENT_SCRIPT
}

buildNewVersion() {
    eko "$VERSION version loading.."

    # rm app and version removed.
    rm -rf $APPNAME

    # if directory exists then  
    [ -d "$APPNAME" ] && { rm -rf "$APPNAME"; }

    # build
    meteor build $APPNAME
    
    # extract build
    tar -zxvf "$APPNAME/$APPNAME.tar.gz" > /dev/null;

    # mv build version
    mv "bundle" $VERSION

    # move current version directory builds
    mv $VERSION $FILEER

    # current version set
    echo $VERSION > $CURRENT_VERSION_FILE
    eko "fileer $VERSION version build completed."

    forever stop $CURRENT_SCRIPT
    forever start -p $APP --pidFile $PID -l $LOG -a -d $SCRIPT
}


# CASES ARGS $1 TYPE
[ "$1" = "version" ] && { currentVersion; }
[ "$1" = "build" ] && { buildNewVersion; }
[ "$1" = "restart" ] && { restartCurrentVersion; }
[ "$1" = "start" ] && { startCurrentVersion; }
[ "$1" = "stop" ] && { stopCurrentVersion; }
