#!/bin/bash

APP="$(pwd)"
BUNDLE="$(pwd)/bundle"
SCRIPT="$BUNDLE/main.js"
PID="$BUNDLE/fileer.pid"
LOG="$BUNDLE/fileer.log"

# exports 
export PORT=3000
export MONGO_URL="mongodb://localhost:27017/fileer"
export ROOT_URL="https://fileer.com"
export DISABLE_WEBSOCKETS=true

forever stop $SCRIPT
forever start -p $APP --pidFile $PID -l $LOG -a -d $SCRIPT
